# Generated by Django 3.2.5 on 2021-07-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210718_0039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_Listings',
            new_name='AllListing',
        ),
        migrations.RenameModel(
            old_name='Closed_Bid',
            new_name='ClosedBid',
        ),
    ]
